### ISSUE TITLE
RPM build failure on Fedora 39/Rawhide (bc nokogiri libxml "foo:colon" thing)

### ISSUE THREAD

**Issue by apjanke** [apjanke/ronn-ng#107]
From downstream [Fedora bug 2226406](https://bugzilla.redhat.com/show_bug.cgi?id=2226406):

ronn-ng FTBFS (Failed To Build From Source) starting on 2023-07-25. Reported in https://github.com/apjanke/ronn-ng/issues/102. They're using Ronn-NG 0.9.1, which was working on earlier Fedora releases, but fails on the recentest.

This ticket is specifically for the building-on-Fedora aspect of that issue, including anything else needed to get it fixed on recent Fedora. (And with only apjanke following it, so the orig reporter doesn't get spammed with comment notifications.)

## Considerations

* [X] May need to relax dep version restrictions for compat with what's in the distro as packages.
  * Yep. See https://github.com/apjanke/ronn-ng/issues/108.
* [X] Check out whatever patches the Fedora package definition has, and maybe upstream them.
  * Done: I checked the [downstream package definition](https://src.fedoraproject.org/rpms/rubygem-ronn-ng/tree/main), and it looks like the only patch they have is the "allow Time class loading in YAML, for Psych 4.x compatibility" handled in https://github.com/apjanke/ronn-ng/issues/80.
  * [X] Oh wait: the [RPM spec file](https://src.fedoraproject.org/rpms/rubygem-ronn-ng/raw/rawhide/f/rubygem-ronn-ng.spec) has an inline patch, too.
    * Did the lib/ronn.rb a-x perm change [here](https://github.com/apjanke/ronn-ng/commit/c7d8a3805fdbd1a38b779896213be025266777d6). Relaxed the mustache version dep in [#108](https://github.com/apjanke/ronn-ng/issues/108).

```text
%patch0 -p1

# Upstream specifies mustache==0.7, but we have 1.1 and it seems to work fine...
%gemspec_remove_dep -g mustache "~> 0.7"

# TODO: file upstream
chmod -x lib/ronn.rb
```

## Details

The downstream bug report's build log is showing the same probably-libxml-related "<dot.> and <foo:colon>" problem as reported in https://github.com/apjanke/ronn-ng/issues/102.

```

+ export CXX
+ cd ronn-ng-0.9.1
+ pushd ./usr/share/gems/gems/ronn-ng-0.9.1
+ ruby -Ilib:test -e 'Dir.glob "./test/test_*.rb", &method(:require)'
Loaded suite -e
Started
F
===============================================================================
Failure: test_angle_bracket_syntax_HTML(RonnTest):
  --- /builddir/build/BUILD/ronn-ng-0.9.1/usr/share/gems/gems/ronn-ng-0.9.1/test/angle_bracket_syntax.html	2023-07-21 18:26:25.630737761 +0000
  +++ /builddir/build/BUILD/ronn-ng-0.9.1/usr/share/gems/gems/ronn-ng-0.9.1/test/angle_bracket_syntax.html.wrong	2023-07-21 18:26:30.440557720 +0000
  @@ -13,5 +13,5 @@
   
   <p>or when <code>&lt;WORD&gt;</code> is enclosed in backticks.</p>
   
  -<p>or when <var>WORD</var> has a <dot.> or <colon>.</colon></dot.></p>
  +<p>or when <var>WORD</var> has a <dot.> or <foo:colon>.</foo:colon></dot.></p>
   </div>
  .
/builddir/build/BUILD/ronn-ng-0.9.1/usr/share/gems/gems/ronn-ng-0.9.1/test/test_ronn.rb:43:in `flunk_with_diff'
/builddir/build/BUILD/ronn-ng-0.9.1/usr/share/gems/gems/ronn-ng-0.9.1/test/test_ronn.rb:96:in `block (2 levels) in <class:RonnTest>'
===============================================================================
Finished in 12.238363415 seconds.
-------------------------------------------------------------------------------
64 tests, 113 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.4375% passed
-------------------------------------------------------------------------------
5.23 tests/s, 9.23 assertions/s
RPM build warnings:
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.fxU1HV (%check)
    %patchN is deprecated (1 usages found), use %patch N (or %patch -P N)
    Bad exit status from /var/tmp/rpm-tmp.fxU1HV (%check)
Child return code was: 1
EXCEPTION: [Error('Command failed: \n # /usr/bin/systemd-nspawn -q -M 08972952575c4e8cba7c146f736e1d6c -D /var/lib/mock/f39-build-44349059-5276931/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.sf0emcyk:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007" --setenv=PS1=<mock-chroot> \\s-\\v\\$  --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c /usr/bin/rpmbuild -bb --noclean --target noarch --nodeps /builddir/build/SPECS/rubygem-ronn-ng.spec\n', 1)]
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/util.py", line 597, in do_with_status
    raise exception.Error("Command failed: \n # %s\n%s" % (command, output), child.returncode)
mockbuild.exception.Error: Command failed: 
 # /usr/bin/systemd-nspawn -q -M 08972952575c4e8cba7c146f736e1d6c -D /var/lib/mock/f39-build-44349059-5276931/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.sf0emcyk:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c /usr/bin/rpmbuild -bb --noclean --target noarch --nodeps /builddir/build/SPECS/rubygem-ronn-ng.spec
```

## References

* [Fedora 39 mass rebuild](https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild)
* [Fedora FTBFS policy](https://docs.fedoraproject.org/en-US/fesco/Fails_to_build_from_source_Fails_to_install/)
* [RPM PR 1 with patch to work around test failure](https://src.fedoraproject.org/rpms/rubygem-ronn-ng/pull-request/1)
* Related issues
  * https://github.com/apjanke/ronn-ng/issues/102
  * https://github.com/apjanke/ronn-ng/issues/108

**Comment by apjanke** [comment]
Okay, I think I have this fixed. But I don't know how to test building an RPM or running ronn-ng against a nokogiri lib that uses the system libxml2 like Fedora does, so I can't fully confirm it. Going to leave this open for a bit and see if I can get the fix confirmed by Fedora folks in https://github.com/apjanke/ronn-ng/issues/102.

**Comment by voxik** [comment]
Oh, wow. I am impressed by your analysis of Fedora .spec file. Thx a lot 😍

**Comment by apjanke** [comment]
In https://github.com/apjanke/ronn-ng/issues/102#issuecomment-1876755212, voxik says Fedora prefers not to mess around with upstream prereleases. And I don't have the time to set up an RPM build testing pipeline on my side. The code fixes I've got are merged to main. So I'm closing this issue, since I think I've got a fix, and dunno how to test it better.

If there's still problems with RPM builds after the 0.10.1 release, please reopen this ticket.
