### ISSUE TITLE
Define lib/app separation and support

### ISSUE THREAD

**Issue by apjanke** [apjanke/ronn-ng#114]
Ronn-NG is intended to be used as an application in the form of a Unix command. It doesn't really support use as a Ruby library. Its Ruby classes in `lib/` are just for internal use.

This is my view of the current Ronn-NG. I'm not sure what the original author Ron Tomayko's view is. I _think_ it's similar, because I didn't see any doco or posts about using Ronn as a Ruby library, there's no doco about a public interface for the Ruby, and to my eye, the code in `lib/` is not arranged or documented for client use.

Issue https://github.com/apjanke/ronn-ng/issues/105 is asking for a Rake task definition that is exposed as client-visible Ruby code, not just a Unix command. We should probably do that.

Maybe alter our internal code structure to make it clear that at the Ruby level, it's for internal use only, and is undocumented and unstable.

Should have a "User Guide.md" doc that discusses this.

## TODO

* [ ] Learn what the Ruby conventions for indicating private-use code vs. consumable library is.
* [ ] Document the public interface for Ronn-NG at both the command and library level.
* [ ] Learn how Rake task definitions work (for https://github.com/apjanke/ronn-ng/issues/105).
* [ ] Look through distros and stuff for other packages that may be using Ronn as a Ruby library.
* [ ] Talk to the Fedora and Debian folks about the split of Ronn-NG in to lib and app packages?
