### ISSUE TITLE
Gobble up n-ronn fixes for 0.10.1

### ISSUE THREAD

**Issue by apjanke** [apjanke/ronn-ng#87]
Per [this discussion in #82](https://github.com/apjanke/ronn-ng/issues/82#issuecomment-1367192841), the RubyGems folks started work on [another "nronn" fork](https://github.com/n-ronn/nronn) and made some enhancements, mostly for maintainability. To keep the tribes united and avoid the need for another fork, pull in their enhancements and see if Ronn-NG can serve that purpose itself.

Roll these out in a 0.10.1 release soon, since it looks like a bunch of Ronn-NG users [have been using the prerelease for the last year or so](https://github.com/apjanke/ronn-ng/issues/82#issuecomment-1368251709)!

## References

* [tnir's PRs to nronn](https://github.com/n-ronn/nronn/issues?q=is%3Aissue+is%3Aclosed)
* [n-ronn/nronn repo](https://github.com/n-ronn/nronn)
 
## TODO

* [x] HTML ["utf-8" charset fix](https://github.com/apjanke/ronn-ng/pull/83)
* [x] Ruby 2.4/2.5 support and test fixes
* [x] Ruby 3.x support
* [x] [Replace Travis CI with GitHub Actions? #88](https://github.com/apjanke/ronn-ng/issues/88)
  * [x] [Consider the `release.yml` workflow separately](https://github.com/n-ronn/nronn/pull/44/files)
* [x] Gem cleanup
* [x] Psych 4.0 test workaround

TODO later in other tickets:

* [Activate GitHub Pages for Ronn-NG and use it for doco #86](https://github.com/apjanke/ronn-ng/issues/86)

Most of these mean pulling in tnir's work from commits in n-ronn. Looks like the commits can't be applied directly because our repos have diverged a bit, mostly from them switching to GH Workflows. I'm new to GH Workflows, so if I adopt that, I'll want to work through it myself instead of just pulling tnir's commits.

**Comment by deivid-rodriguez** [comment]
@apjanke Even if you can't cherry-pick commits directly, you can still manually add a "Co-authored-by:` line to the commit message to give proper attribution to the author of the changes. See https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors.

**Comment by apjanke** [comment]
I think I've pulled in all the major nronn fixes & enhancements now (except for enabling GitHub Pages as a doco site, which I'll do later), and I did a big Git commit history rewrite to tidy things up, and add "Co-authored-by:" attribution for @tnir on the relevant commits. It's merged to main now.

A 0.10.1pre2 prerelease will be coming out soon.

**Comment by apjanke** [comment]
Reopened this issue to include doing the 0.10.1 release itself, since that's going to need some further work, and I don't want to create a separate ticket for it and split the conversation/record.

There's some fiddly stuff with regenerating the ronn man pages, plus the gem publishing process, which will need at least one more prerelease for review, and I have to fix the broken Ruby/gems environment on my local Mac and make sure the Ronn-NG bundled stuff works with a "proper" Ruby 3.x environment.

**Comment by apjanke** [comment]
I think I've got my Ruby environment and RubyGems release act together a bit more now. Mostly boils down to "you need to set $GEM_HOME if you're running on a box with a locked-down system Ruby/Gems installation", I think.

I have published a new 0.10.1.pre2 preview to RubyGems, from the branch `WIP/https-ify`. If that works out, I'll merge it and send it out as the real 0.10.1 Ronn-NG release.

**Comment by apjanke** [comment]
Okay, still looking good. I've merged the pending changes to `master`, made a new 0.10.1.pre3 release, and published it to RubyGems. If no complaints in a couple days, I'll make an actual 0.10.1 release.

**Comment by apjanke** [comment]
Uh, yeah: I'm working for a startup at my day job, and things got busy, and then our bank collapsed, and stuff.

But in terms of this code for ronn-ng, no issues, and I'll try to get a release rolled out this weekend! Sorry for the delay here.

**Comment by thesamesam** [comment]
Oh bloody hell, I'm sorry! Please don't worry about this, I just came across it and got curious.

But many thanks, whenever it happens, be it this weekend or many months away. I hope things are getting a bit better for you now!

**Comment by apjanke** [comment]
No worries! My work survived the SVB blowup just fine, and I do this ronn-ng stuff for fun. It's not a burden, and I appreciate getting engagement from users like this. :)

**Comment by apjanke** [comment]
Marking this as closed again. The fixes are pulled in and the tests are passing again now that https://github.com/apjanke/ronn-ng/issues/102 is (I think) fixed, so an 0.10.1 release will be coming out soon.
